name: backend-deploy

on:
  push:
    branches:
      - sprint-BE
  workflow_dispatch: # (2) 수동 실행

jobs:
  build:
    runs-on: ubuntu-latest # (3)

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # (4)

      - name: Set up JDK 11
        uses: actions/setup-java@v1 # (5)
        with:
          java-version: 11

      - name: go to back directory
        run: cd ./back
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew # (6)
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build # (7)
        shell: bash